### ISSUE TITLE
Sanbox login issue

### ISSUE THREAD

**Issue by airtel121** [AuthorizeNet/inperson-sdk-android#12]
In This code when I try to login with my sandbox credentials it is not allowing me to login. there is one "LoginActivity.java" file which contains "deviceID" field. i don't know from where to get this device id. There is one comment as well like "set your_device_ID. You need to get a registered device id from your MINT account and set the id here"

so my question is what is MINT Account? is there any other parameters we need to set?

**Comment by amimishr** [comment]
Hi Airtel121,

MINT stands for Merchant Interface. To use Authorize.Net in person sdk and accept the payments, you need to sign up as a merchant in Authorize.Net portal.

The sandbox account can be created by following the below link -

https://developer.authorize.net/hello_world/sandbox/

You can also create a production account by following below link - 

https://www.authorize.net/solutions/merchantsolutions/pricing/

Regards
