### ISSUE TITLE
Error FileNotFoundException

### ISSUE THREAD

**Issue by vishaln2it** [AuthorizeNet/inperson-sdk-android#15]
AuthorizeNet/inperson-sdk-android => got error like java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.bbpos.emvswipe.ui/settings.txt: open failed: ENOENT (No such file or directory) 

we want to use authorize.net sdk in Android application but didn't get any working sample application(demo).
so need your help how to use authorize.net for American Express ,Discover ,JCB ,Diners Club/ Carte Blanch ,Visa ,Master Card and on-line bank transaction so need your help devlope authorize.net sdk in our app for payment.

so we need your help for use authorize.net sdk in our app. which sdk is better AuthorizeNet/inperson-sdk-android or AuthorizeNet/accept-sample-android ? please provide any working sample code (demo)

**Comment by ywang7** [comment]
Can you check if you have write access to /storage/emulated/0/Android/data/com.bbpos.emvswipe.ui/settings.txt ? If the file exists, please delete the folder com.bbpos.emvswipe.ui and try again.

As for which SDK to use, inperson-sdk is for card present use case where you have card reader attached to the phone and customer hand in the card to swipe or insert; accept-sdk is for online processing where you enter the credit card info and send to Authorize.net for processing.

Hope that helps.
For more infomation, you can check our developer website http://developer.authorize.net/.
