### ISSUE TITLE
Implement Payment for End user in Native Android/iOS App

### ISSUE THREAD

**Issue by vishaln2it** [AuthorizeNet/inperson-sdk-android#16]
Hello, We are using inperson-sdk-android/iOS and Accept-sdk-android/iOS for Implementing payment Process for Bank Transfer and Credit Card. Please note that we are using Payment Process in Mobile Application in Android/iOS. Is it possible that End User from any where in the World perform Transaction using Authorize.Net in Native Android/iOS Application ?
Can you suggest which sdk we can use for Payment Process ? If possible can you please provide Demo for End User Payment Process ?

**Comment by brianmc** [comment]
Is the end-user of your mobile application a consumer (i.e. the cardholder) or a merchant (i.e. the business accepting payment)?  If it is consumer you should use Accept SDK, if merchant you should use InPerson SDK.  Both have great sample apps.
