### ISSUE TITLE
TRANSACTION_DECLINED even tho network transaction reports success

### ISSUE THREAD

**Issue by Mindelt** [AuthorizeNet/inperson-sdk-android#19]
Hey

we are using a chip reader from your device loaner program and android in-person SDK.
During development we have noticed a strange SDK behavior, which we would prefer to clear up before going to production.

As mentioned here http://forms.authorize.net/emvDeviceLoanerProgram we only use Visa cards for sandbox requests.

What we have observed is that with the vast majority of Visa cards the first web request the in-person sdk attempts is reported as TRANSACTION_DECLINED in our EMVTransactionListener. onEMVReadError callback, although when we inspect the app network traffic, we can see that the authOnlyTransaction was a success, we get the email receipt, and the transaction is visible in the sandbox website unsettled transactions
list.

We have found some Visa cards that work with no problem, but have no idea what makes them special.

Transaction with transactionId: 60021414341 on sandbox API is an example of the transaction which was a success, but the in-person SDK reported it as a failure.

What may cause the difference in status reported from API and in-person sdk?

Appreciate your help!

**Comment by ptaneja** [comment]
Hello,

Sorry for the delay in response. We could reproduce the issue. Fix is available in latest commit, please integrate the latest aar file and try. Thank you!

**Comment by ncpga** [comment]
Thank you for fixing the issue impacting customers.

Sent from my iPhone

On May 2, 2017, at 7:11 PM, Pankaj Taneja <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello,

Sorry for the delay in response. We could reproduce the issue. Fix is available in latest commit, please integrate the latest aar file and try. Thank you!
