### ISSUE TITLE
reading EMV encrypted BLOB android

### ISSUE THREAD

**Issue by AndroidLoaders** [AuthorizeNet/inperson-sdk-android#27]
I'm not able to get EMV encrypted blob which is required for creation of new CrediCard object.
Also i'm not able to get that in README.md file provided code for EMVTrasaction works only for AnywhereCommerce device or for both(AnywhereCommerce and IdTech).
If it works only for AnywhereCommerce then which code i run for IdTech device which also supported by this SDK and additionally how do i get that which card reader device is connected to Android Mobile/tablet and how to get that card reader device detail(Like blob) and Card which is swiped through that device.
Also RECORD_AUDIO and STORAGE READ and WRITE permissions are needed?
Please guid me in proper direction.
When user clicks on pay button following code runs

This is my code :
private class CreateTransaction extends AsyncTask<Integer, Integer, Integer> {

        //String cardNumber = "", expirationMonth = "", expirationYear = "", cvv = "";
          private static final String IDTechTestBlob = "3032434530313830314634413232303030333942252a353435392a2a2a2a2a2a2a2a333830305e504157414e20524157414c20202020202020202020202020202f5e2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a2a3f2a3b353435392a2a2a2a2a2a2a2a333830303d2a2a2a2a2a2a2a2a2a2a2a2a2a2a3f2a35343843443545353433463145313945313037454145444532434242384246413730423430374633414234323834363330314335453443323137344534453845354130373730303431453037443934443632313531303133383241344342413535354133313434334443353839354341443332393638433338383634383736454645393535464646423344413930423534394342413137413631334345423139373241443539384446453241333437363145463544424241413039414237443043354232434134333835444131354437333230363331433730434238373138323643464345334144334133444434443539433630413732364532464132454530343239313341344232454538354443434135444338413443384533343436313845393935303138303144393745383443304336324437384135354332413545333130323436303031324230333234323030303237373336463033";

        net.authorize.mobile.Result loginResult;

        Order order = null;
        Merchant testMerchant = null;
        Customer customer = null;

        //net.authorize.aim.Result authCaptureResult = null;

        @Override
        protected void onPreExecute() {
            super.onPreExecute();

            progressDialog = new ProgressDialog(activity);
            progressDialog.setCancelable(false);
            progressDialog.setMessage("Requesting for payment...");
            progressDialog.setProgressStyle(ProgressDialog.STYLE_SPINNER);
            progressDialog.show();
        }

        @Override
        protected Integer doInBackground(Integer... params) {
            try {
                //first we need to login and Create authentication method based on login, password and device ID
                PasswordAuthentication passAuth = PasswordAuthentication.createMerchantAuthentication(getString(R.string.userName), getString(R.string.password), "InpersonSDK-Android-test");

                //Create merchant object using authentication method
                testMerchant = Merchant.createMerchant(Environment.SANDBOX, passAuth);
                testMerchant.setDeviceType(DeviceType.WIRELESS_POS);
                testMerchant.setMarketType(MarketType.RETAIL);

                //Create login request and populate mobile device field
                net.authorize.mobile.Transaction loginTransaction = testMerchant.createMobileTransaction(net.authorize.mobile.TransactionType.MOBILE_DEVICE_LOGIN);
                net.authorize.data.mobile.MobileDevice mobileDevice = net.authorize.data.mobile.MobileDevice.createMobileDevice("InpersonSDK-Android-test", "Device description", "425-555-0000", "Android");
                loginTransaction.setMobileDevice(mobileDevice);
                //post login request to Authorize.net Gateway
                loginResult = (net.authorize.mobile.Result) testMerchant.postTransaction(loginTransaction);

                if (loginResult.isOk()) {
                    System.out.println("TAG --> Login Successful");
                    //if login succeeded, populate session token in the Merchant object
                    SessionTokenAuthentication sessionTokenAuthentication = SessionTokenAuthentication.createMerchantAuthentication(testMerchant.getMerchantAuthentication().getName(), loginResult.getSessionToken(), "InpersonSDK-Android-test");
                    if ((loginResult.getSessionToken() != null) && (sessionTokenAuthentication != null)) {
                        testMerchant.setMerchantAuthentication(sessionTokenAuthentication);
                    }

                    creditCard = CreditCard.createCreditCard();
                    creditCard.setCardPresenseType(net.authorize.data.creditcard.
                            CreditCardPresenceType.CARD_PRESENT_ENCRYPTED);
                    creditCard.getSwipperData().setMode(SwiperModeType.DATA);
                    //the following field is the data converted into HEX string coming from the reader
                    creditCard.getSwipperData().setEncryptedData(IDTechTestBlob);
                    //the FID for the reader
                    creditCard.getSwipperData().setDeviceInfo("4649443d4944544543482e556e694d61672e416e64726f69642e53646b7631");
                    //the Encryption method used by the reader, should be TDES for IDTech
                    creditCard.getSwipperData().setEncryptionAlgorithm(SwiperEncryptionAlgorithmType.
                            TDES);
                    //}

                    publishProgress(50);

                    //create order item and add to transaction object
                    order = Order.createOrder();
                    OrderItem oi = OrderItem.createOrderItem();
                    oi.setItemId("2");
                    oi.setItemName("This is sparta");
                    oi.setItemDescription("Goods");
                    oi.setItemPrice(new BigDecimal(200.0));  //itemPrice/quantity
                    oi.setItemQuantity("2");
                    oi.setItemTaxable(false);
                    order.addOrderItem(oi);
                    order.setTotalAmount(new BigDecimal(1.00));

                    customer = Customer.createCustomer();
                    customer.setId("12");  //Login user id
                    customer.setCustomerId("12");  //Login user id
                    customer.setAddress("Raj Wold Mall, XYZ");
                    customer.setCompany("ABCD PVT. LTD.");
                    customer.setCity("Bangol");
                    customer.setCustomerType(CustomerType.INDIVIDUAL);
                    customer.setCountry("India");
                    customer.setState("Bangol");
                    customer.setFirstName("Harshal");
                    customer.setLastName("Bhatt");
                    customer.setEmail("omish.mehta@gmail.com");
                    customer.setZipPostalCode("123465");

                    Address address = Address.createAddress();
                    address.setAddress("ABCD Infotech, D-Mart,Bangol");
                    address.setPhoneNumber("1234567890");
                    address.setZipPostalCode("123456");
                    address.setCompany("ABC Infotech");
                    address.setCountry("India");
                    address.setState("Bangol");
                    address.setCity("Bangol");
                    address.setFirstName("Harshal");
                    address.setLastName("Bhatt");

                    customer.setShipTo(address);
                    //customer.setBillTo(address);

                    publishProgress(75);

                } else {
                    //handle login errors in here
                }
            } catch (Exception e) {
                System.out.println("TAG Exception --> " + e.getMessage());
            }
            return 0;
        }

        @Override
        protected void onProgressUpdate(Integer... values) {
            super.onProgressUpdate(values);
            if (values[0] == 50) {
                if (progressDialog != null) {
                    progressDialog.setMessage("Getting customer details...");
                }
            } else if (values[0] == 75) {
                if (progressDialog != null) {
                    progressDialog.setMessage("Please wait ... making transaction");
                }
            }
        }

        @Override
        protected void onPostExecute(Integer response) {
            super.onPostExecute(response);
            try {

                if (creditCard != null && creditCard.getCreditCardNumber() != null) {
                    startEMVTransaction(customer, order, testMerchant, creditCard);
                } else {
                    if (progressDialog != null) {
                        progressDialog.dismiss();
                    }
                    Toast.makeText(activity, "Card number : " + creditCard.getCreditCardNumber(),
                            Toast.LENGTH_SHORT).show();
                    Toast.makeText(activity, "Card Not Found", Toast.LENGTH_SHORT).show();
                }
            } catch (Exception e) {
                System.out.println("TAG Exception --> " + e.getMessage());
            }
        }
    }

    private void startEMVTransaction(Customer customer, Order order, Merchant merchant,
                                     CreditCard creditCard) {
        EMVTransaction emvTransaction = EMVTransactionManager.createEMVTransaction(merchant,
                order.getTotalAmount());
        emvTransaction.setCustomer(customer);
        emvTransaction.setOrder(order);
        emvTransaction.setCreditCard(creditCard);
        emvTransaction.setEmvTransactionType(EMVTransactionType.GOODS);
        EMVTransactionManager.startEMVTransaction(emvTransaction, this, activity);
    }

@Override
    public void onEMVTransactionSuccessful(Result result) {
        if (progressDialog != null) {
            progressDialog.dismiss();
        }
        Toast.makeText(activity, "EMVTransactionSuccessful", Toast.LENGTH_SHORT).show();
        if (result != null) {
            if (result.isApproved()) {
                Toast.makeText(activity, "Payment Successful", Toast.LENGTH_SHORT).show();
                HashMap<String,String> map = result.getEmvTlvMap();
                Toast.makeText(activity, "4f --> "+map.get("4f"), Toast.LENGTH_SHORT).show();
                Toast.makeText(activity, "4f --> "+map.get("4f"), Toast.LENGTH_SHORT).show();
                Toast.makeText(activity, "4f --> "+map.get("4f"), Toast.LENGTH_SHORT).show();
                Toast.makeText(activity, result.getXmlResponse(), Toast.LENGTH_SHORT).show();
                Toast.makeText(activity, result.getResponseText(), Toast.LENGTH_LONG).show();
                Toast.makeText(activity, "A/c no. : " + result.getAccountNumber(), Toast.LENGTH_SHORT).
                        show();
                Toast.makeText(activity, "Transaction Id : " + result.getTransId(), Toast.LENGTH_SHORT).
                        show();
                Toast.makeText(activity, "Tip amount : " + result.getTipAmount(), Toast.LENGTH_SHORT).
                        show();
            } else {
                Toast.makeText(activity, result.getResponseText(), Toast.LENGTH_LONG).show();
                Toast.makeText(activity, result.getTransactionResponseMessages().get(0).getReasonText(),
                        Toast.LENGTH_SHORT).show();
                Toast.makeText(activity, result.getMessages().get(0).getText(), Toast.LENGTH_SHORT).
                        show();
                Toast.makeText(activity, result.getXmlResponse(), Toast.LENGTH_SHORT).show();
            }
        }
    }

    @Override
    public void onEMVReadError(EMVErrorCode emvErrorCode) {
        if (progressDialog != null) {
            progressDialog.dismiss();
        }
        Toast.makeText(activity, "EMVReadError", Toast.LENGTH_SHORT).show();
        if (emvErrorCode != null) {
            Toast.makeText(activity, "Error Code : " + emvErrorCode.getError(), Toast.LENGTH_LONG).
                    show();
            Toast.makeText(activity, "Error String : " + emvErrorCode.getErrorString(),
                    Toast.LENGTH_LONG).show();
        }
    }

    @Override
    public void onEMVTransactionError(Result result, EMVErrorCode emvErrorCode) {
        if (progressDialog != null) {
            progressDialog.dismiss();
        }
        Toast.makeText(activity, "EMVTransactionError", Toast.LENGTH_SHORT).show();
        if (result != null) {
            Toast.makeText(activity, result.getResponseText(), Toast.LENGTH_SHORT).show();
            Toast.makeText(activity, result.getXmlResponse(), Toast.LENGTH_SHORT).show();
            if (result.getMessages() != null && result.getMessages().size() > 0) {
                Toast.makeText(activity, "Message : " + result.getMessages().get(0).getText(),
                        Toast.LENGTH_LONG).show();
                Toast.makeText(activity, "Message string : " + result.getMessages().get(0).getValue(),
                        Toast.LENGTH_LONG).show();
            }
            if (result.getTransactionResponseMessages() != null &&
                    result.getTransactionResponseMessages().size() > 0) {
                Toast.makeText(activity, "Response Reason : " +
                                result.getTransactionResponseMessages().get(0).getReasonText(),
                        Toast.LENGTH_LONG).show();
            }
        }
    }
}

**Comment by ywang7** [comment]
Hi AndroidLoaders,

I think there are two problems here:
1. not being able to get encrypted blob: if you are referring to the online request that the card reader send to Authorize.net for processing, that blob is encrypted and not supposed to be accessible by the application; if you mean the EMV TLV response you can retrieve that by `result.getEmvTlvMap()`

2. Support for IDTech readers: for now only swipe reader from IDTech(Shuttle) is supported, however reader support does not ship with EMV SDK since it is not capable of handling the whole transaction flow end-to-end, if you want to try that you have the option to get the blob from reader using IDTech SDK and construct the request using `CreateTransactionRequest` and post it to Authorize.net gateway, please refer to this issue for more details:
https://github.com/AuthorizeNet/inperson-sdk-android/issues/18

Please let me know if there are further questions.

**Comment by AndroidLoaders** [comment]
Hey... 
Thank for proper guideline and be helpful..

If I have any doubt I'll post it to this link.Please be helpful and guide me..

Thanks..

**Comment by arn95** [comment]
Record Audio must be because some swipers connect through the audio jack.

**Comment by AndroidLoaders** [comment]
I'm not able to understand that how do i know that user has swiped credit card and now i have to request for payment to authorize.net(i.e to call EMVTransactionManager.startEMVTransaction(emvTransaction, this, activity);) 

Please guid me guys.

**Comment by amimishr** [comment]
@AndroidLoaders ,

The method EMVTransactionManager.startEMVTransaction will take care of reading card data from the reader(either through Chip/Swipe), calling back end APIs to initiate transaction. The method will send you the transaction result via EMVTransactionListener callback methods. This is to make it easier for developers to avoid worrying about detecting card swipe event and calling transaction APIs separately.

Regards,
Amit
