### ISSUE TITLE
How to detect user has swiped and now request for payment Authorize.net

### ISSUE THREAD

**Issue by AndroidLoaders** [AuthorizeNet/inperson-sdk-android#29]
I need to process payment using credit card swiper(Like AnywhereCommerce) but I'm not able to understand that how do i know that user has swiped credit card and now i have to request for payment to authorize.net(i.e to call EMVTransactionManager.startEMVTransaction(emvTransaction, this, activity);)

To detect swipe is there any callback method ? if yes then what is the name of that method and how do i use it?

Please guid me guys.

**Comment by ywang7** [comment]
Hi AndroidLoaders,

Currently we support AnywhereCommerce C2X reader for doing EMV or swipe transactions:
https://partner.posportal.com/authorizenet/auth/anywherecommerce-walker-c2x-for-authorizenet.html

If you are using the EMV transaction flow, the callbacks are inside `EMVTransactionListener` class. However to make the transaction secure the SDK will take over the transaction end-to-end and developers will not be able to access the chip data at any point. All data will be formatted by SDK and posted to Authorize.Net gateway .

Hope this answers your question, if not could you provide more details on why you would need to access chip/swipe data?

Thanks,
Alex

**Comment by AndroidLoaders** [comment]
Dear sir,

My requirement is to swipe card and create payment successful but if i'm not getting any details from swiper like (user has swiped its card and now you can proceed to Authorize.net for payment) then user will think that payment is not working and leave an app.

This is the reason for asking this question and yes, i really do not want to access chip/swipe data because  
it can insecure user's privacy and more over, now i can explain clearly to my client that this way device and payment system works and also provide this questions links too if needed.

Thanks sir for helping, if i have more questions regarding payment or authorize.net payment gateway,i'll raise question to this link.

Thank you

**Comment by amimishr** [comment]
@AndroidLoaders ,

The method EMVTransactionManager.startEMVTransaction will take care of reading card data from the reader(either through Chip/Swipe), calling back end APIs to initiate transaction. The method will send you the transaction result via EMVTransactionListener callback methods. This is to make it easier for developers to avoid worrying about detecting card swipe event and calling transaction APIs separately.

Regards,
Amit
