### ISSUE TITLE
Support for below api 21 in android

### ISSUE THREAD

**Issue by AndroidLoaders** [AuthorizeNet/inperson-sdk-android#36]
Hi sir,

This sample contains .aar file that supports only devices with api 21 and above. Is there any other way to provide support devices running below api 21 ? or any other library for android to support below api 21 by AuthorizeNet .. ?

**Comment by brianmc** [comment]
Hi @AndroidLoaders we are aware there's still quite a bit of kitkat out there but at the current time we're not planning to support anything lower than 21.  General advice from Google is to try to support 90% of devices so we're a little below that but hopefully there'll be a fairly rapid decrease in those versions.

https://developer.android.com/about/dashboards/index.html
