### ISSUE TITLE
Refund Integration

### ISSUE THREAD

**Issue by AndroidLoaders** [AuthorizeNet/inperson-sdk-android#41]
We need to implement refund feature for android from our app as we have integrated inperson-sdk in our app..
We have 2 options for payment, first is, user will manually enter card details and make payment and another option is by attaching c2x card reader to make payment and in both of the cases we are providing refund feature.
We are searching for refund api from android but not able to get things.We need help to integrate refund if anyone has integrated or has some idea about refund...

**Comment by JubinMathai** [comment]
Hi @AndroidLoaders ,

Can you share a sample code in which you integrated the sdk. I am able to create merchant but not able make payments. When I try to make payment I'm getting following "Unknown device error, please try again"

I used the sample app provided in their sdk. 
Any help would be appreciated.

**Comment by amimishr** [comment]
Dear @AndroidLoaders ,

Yes, you can do the refund transaction. 

To do so, create a new transaction with type TransactionType.CREDIT and post it.

Note:
1- The refund action is allowed only if the transactions state is "settled"
2- If transaction is still under pending settlement, you can VOID it.

**Comment by amimishr** [comment]
Hi @JubinMathai ,

Could you please provide more information such as what is the mobile phone/tablet model, Android OS version you are using?

**Comment by AndroidLoaders** [comment]
Hi @JubinMathai ,

I'm using this code for swipe transaction.Please verify it with your code and let us know whether we doing right or not  

Also provide your code too for more clarification..This code redirecting us to next page which is provided by authorize.net sdk

    //TODO : For payment using swipe card through swiper device
    private class CreateSwipeTransaction extends AsyncTask<Void, Integer, Void> {

        EMVTransaction emvTransaction = null;

        CreateSwipeTransaction() {
        }

        @Override
        protected void onPreExecute() {
            super.onPreExecute();
            progressDialog.show();
        }

        @Override
        protected Void doInBackground(Void... voids) {
            try {
                String deviceId = Build.MANUFACTURER + "_" + Build.MODEL;
                //TODO : First we need to login and Create authentication method based on login, password and device ID
                PasswordAuthentication passAuth = PasswordAuthentication.createMerchantAuthentication(getString(R.string.anet_userName), getString(R.string.anet_password), deviceId);

                //TODO : Create merchant object using authentication method
                Merchant testMerchant = Merchant.createMerchant(Environment.SANDBOX, passAuth);
                testMerchant.setDeviceType(DeviceType.WIRELESS_POS);
                testMerchant.setMarketType(MarketType.RETAIL);

                net.authorize.mobile.Transaction loginTransaction = testMerchant.createMobileTransaction(net.authorize.mobile.TransactionType.MOBILE_DEVICE_LOGIN);
                net.authorize.data.mobile.MobileDevice mobileDevice = net.authorize.data.mobile.MobileDevice.createMobileDevice(deviceId, "Device description", "425-555-0000", "Android");
                loginTransaction.setMobileDevice(mobileDevice);

                publishProgress(1);

                //TODO : Post login, request to Authorize.net Gateway
                net.authorize.mobile.Result loginResult = (net.authorize.mobile.Result) testMerchant.postTransaction(loginTransaction);

                System.out.println("TAG -- ANET -- Merchant Login --> " + loginResult.getResultCode());
                System.out.println("TAG -- ANET -- Merchant Login --> " + loginResult.getMessages().get(0).getText());

                if (loginResult.isOk()) {
                    System.out.println("TAG -- ANET --> Login Successful");
                    //if login succeeded, populate session token in the Merchant object
                    SessionTokenAuthentication sessionTokenAuthentication = SessionTokenAuthentication.createMerchantAuthentication(testMerchant.getMerchantAuthentication().getName(), loginResult.getSessionToken(), "Test EMV Android");//InpersonSDK-Android-test
                    if (loginResult.getSessionToken() != null)
                        testMerchant.setMerchantAuthentication(sessionTokenAuthentication);

                    publishProgress(2);

                    //TODO : Create customer for tracking details
                    Customer customer = Customer.createCustomer(CustomerType.INDIVIDUAL);
                    customer.setEmail(((verifiedEmail != null) && (!TextUtils.isEmpty(verifiedEmail))) ? verifiedEmail : getString(R.string.not_available));
                    customer.setPhone(((verifiedPhone != null) && (!TextUtils.isEmpty(verifiedPhone))) ? verifiedPhone : getString(R.string.not_available));

                    emvTransaction = EMVTransactionManager.createEMVTransaction(testMerchant, new BigDecimal(finalPayableAmount));
                    emvTransaction.setEmvTransactionType(EMVTransactionType.GOODS);
                    emvTransaction.setCustomer(customer);

                    //TODO : Create payment method.
                    EMVTransactionManager.TerminalMode terminalMode = EMVTransactionManager.TerminalMode.SWIPE_OR_INSERT;
                    EMVTransactionManager.setTerminalMode(terminalMode);

                    publishProgress(3);

                    EMVDeviceConnectionType deviceConnectionType = EMVDeviceConnectionType.AUDIO;
                    EMVTransactionManager.setDeviceConnectionType(deviceConnectionType);
                }
            } catch (Exception e) {
                Crashlytics.logException(e);
                System.out.println("TAG Exception --> " + e.getMessage());
                cancel(true);
            }
            return null;
        }

        @Override
        protected void onProgressUpdate(Integer... values) {
            super.onProgressUpdate(values);
            if (values[0] == 1) progressDialog.setMessage(getString(R.string.anet_authentication));
            else if (values[0] == 2)
                progressDialog.setMessage(getString(R.string.anet_authentication_successfull));
            else if (values[0] == 3)
                progressDialog.setMessage(getString(R.string.anet_request_payment));
        }

        @Override
        protected void onPostExecute(Void aVoid) {
            super.onPostExecute(aVoid);
            EMVTransactionManager.startEMVTransaction(emvTransaction, iemvTransaction, activity);
            progressDialog.dismiss();
        }
}

EMVTransactionManager.QuickChipTransactionSessionListener iemvTransaction = new EMVTransactionManager.QuickChipTransactionSessionListener() {
        @Override
        public void onReturnBluetoothDevices(final List<BluetoothDevice> bluetoothDeviceList) {
            // setup the alert builder
        }

        @Override
        public void onBluetoothDeviceConnected(BluetoothDevice bluetoothDevice) {
            Log.d("Bluetooth device", "bluetooth device connected : " + bluetoothDevice.getName());
        }

        @Override
        public void onTransactionStatusUpdate(String transactionStatus) {

        }

        @Override
        public void onPrepareQuickChipDataSuccessful() {
        }

        @Override
        public void onPrepareQuickChipDataError(EMVErrorCode error, String cause) {
        }

        @Override
        public void onEMVTransactionSuccessful(net.authorize.aim.emv.Result result) {
            System.out.println("TAG -- ANET --> onEMVTransactionSuccessful called");
        }

        @Override
        public void onEMVReadError(EMVErrorCode emvError) {
            System.out.println("TAG -- ANET --> onEMVReadError called");
        }

        @Override
        public void onEMVTransactionError(net.authorize.aim.emv.Result result, EMVErrorCode emvError) {
            System.out.println("TAG -- ANET --> onEMVTransactionError called");
        }
    };

**Comment by AndroidLoaders** [comment]
Dear @amimishr ,

Thanks sir for redirecting us..but could you please provide more information that how do we know that transactions state is already SETTLED and same thing for VOID transactions state as we are getting mail for settled transactions on next day

**Comment by amimishr** [comment]
@AndroidLoaders 

Once you have executed the transaction, you will receive a "transactionID". Using this transaction ID, you can call transaction details API, by creating a transaction with transaction type as 
 - net.authorize.reporting.TransactionType.GET_TRANSACTION_DETAILS,  which will give you the current state as well as other details about the given transaction.

**Comment by AndroidLoaders** [comment]
Thanks sir, for quick response.

If i'll have any further questions/doubts i'll post through channel..

Thanks sir

**Comment by AndroidLoaders** [comment]
Respected sir, 

As per your guidelines we have implemented code to get transaction details from transaction id and also able to differentiate when to void and refund transaction ... here is a code so that other people can review and implement it..

**## Query** : But we are not getting how can we implement refund and void feature like to get transaction detail you provided package name net.authorize.reporting.TransactionType.GET_TRANSACTION_DETAILS.
So from package name we're able get how to implement.

So please provide us some more detailed picture for same or if any working demo and if there is any correction in below code then please inform us so that we can provide best quality to our client.

//TODO : Get details of particular transaction.
    private class GetTransactionDetails extends AsyncTask<String, Integer, net.authorize.reporting.Result> {

        GetTransactionDetails() {
        }

        @Override
        protected void onPreExecute() {
            super.onPreExecute();
            progressDialog.setMessage(getString(R.string.anet_authentication));
            progressDialog.show();
        }

        @Override
        protected net.authorize.reporting.Result doInBackground(String... transactionId) {
            net.authorize.reporting.Result tDetailedResult = null;
            try {
                String deviceId = Build.MANUFACTURER + "_" + Build.MODEL;
                //TODO : First we need to login and Create authentication method based on login, password and device ID
                PasswordAuthentication passAuth = PasswordAuthentication.createMerchantAuthentication(getString(R.string.anet_userName), getString(R.string.anet_password), deviceId);

                //TODO : Create merchant object using authentication method
                Merchant testMerchant = Merchant.createMerchant(Environment.SANDBOX, passAuth);
                testMerchant.createReportingTransaction(TransactionType.GET_TRANSACTION_DETAILS);

                net.authorize.mobile.Transaction loginTransaction = testMerchant.createMobileTransaction(net.authorize.mobile.TransactionType.MOBILE_DEVICE_LOGIN);
                net.authorize.data.mobile.MobileDevice mobileDevice = net.authorize.data.mobile.MobileDevice.createMobileDevice(deviceId, "Device description", "425-555-0000", "Android");
                loginTransaction.setMobileDevice(mobileDevice);

                //TODO : Post login, request to Authorize.net Gateway
                net.authorize.mobile.Result loginResult = (net.authorize.mobile.Result) testMerchant.postTransaction(loginTransaction);
                if (loginResult.isOk()) {
                    publishProgress(1);
                    Thread.sleep(1000);

                    SessionTokenAuthentication sessionTokenAuthentication = SessionTokenAuthentication.createMerchantAuthentication(testMerchant.getMerchantAuthentication().getName(), loginResult.getSessionToken(), "Test EMV Android");//InpersonSDK-Android-test
                    if (loginResult.getSessionToken() != null)
                        testMerchant.setMerchantAuthentication(sessionTokenAuthentication);

                    publishProgress(2);
                    Thread.sleep(1000);

                    ReportingDetails details = ReportingDetails.createReportingDetails();
                    details.setTransactionId(transactionId[0]);

                    net.authorize.reporting.Transaction transaction = Transaction.createTransaction(testMerchant, TransactionType.GET_TRANSACTION_DETAILS);
                    transaction.setReportingDetails(details);

                    tDetailedResult = (Result) testMerchant.postTransaction(transaction);
                }
            } catch (Exception e) {
                System.out.println("TAG --> " + e.getMessage());
            }
            return tDetailedResult;
        }

        @Override
        protected void onProgressUpdate(Integer... values) {
            super.onProgressUpdate(values);
            if (values[0] == 1)
                progressDialog.setMessage(getString(R.string.anet_authentication_successfull));
            else if (values[0] == 2)
                progressDialog.setMessage(getString(R.string.anet_request_transaction_details));
        }

        @Override
        protected void onPostExecute(net.authorize.reporting.Result tDetailedResult) {
            super.onPostExecute(tDetailedResult);
            try {
                progressDialog.dismiss();
                if (tDetailedResult != null) {
                    System.out.println("TAG -- ANET --> response : " + tDetailedResult.getXmlResponse());
                    List<MessageType> mTypeList = tDetailedResult.getMessages();
                    if (mTypeList != null && mTypeList.size() > 0) {
                        String rCode = mTypeList.get(0).getValue();
                        System.out.println("TAG -- ANET --> rCode : " + rCode);
                        if (rCode.equals("I00011"))
                            CommonUtility.alert(activity, getString(R.string.cancel_transaction), getString(R.string.anet_merchant_not_activated));
                        else if (rCode.equals("E00001"))
                            CommonUtility.alert(activity, getString(R.string.cancel_transaction), getString(R.string.anet_system_error));
                        else if (rCode.equals("E00011")) //TODO : No permission
                            new AlertDialog.Builder(activity).setTitle(getString(R.string.cancel_transaction)).setMessage(getString(R.string.anet_no_permission_to_get_transaction_details)).create().show();
                        else if (rCode.equals("I00001")) {//TODO : Successfully got details
                            ReportingDetails details = tDetailedResult.getReportingDetails();
                            List<TransactionDetails> list = details.getTransactionDetailList();
                            if (list != null && list.size() > 0) {
                                TransactionDetails tDetails = list.get(0);
                                TransactionStatusType statusType = tDetails.getTransactionStatus();
                                String text = "";
                                if ((statusType == TransactionStatusType.CAPTURED_PENDING_SETTLEMENT))
                                    Toast.makeText(activity, text = "Transaction can be voided", Toast.LENGTH_SHORT).show();
                                else if (statusType == TransactionStatusType.SETTLED_SUCCESSFULLY)
                                    Toast.makeText(activity, text = "Transaction can request for refund", Toast.LENGTH_SHORT).show();
                                else if (statusType == TransactionStatusType.VOIDED)
                                    Toast.makeText(activity, text = "Transaction already voided", Toast.LENGTH_SHORT).show();
                                else if (statusType == TransactionStatusType.REFUND_PENDING_SETTLEMENT)
                                    Toast.makeText(activity, text = "Transaction refund already in progress", Toast.LENGTH_SHORT).show();
                                else if (statusType == TransactionStatusType.REFUND_SETTLED_SUCCESSFULLY)
                                    Toast.makeText(activity, text = "Transaction already refunded", Toast.LENGTH_SHORT).show();
                                System.out.println("TAG -- ANET --> text : " + text);
                            }
                        }
                    }
                } else
                    CommonUtility.alert(activity, getString(R.string.cancel_transaction), getString(R.string.anet_null_response));
            } catch (Exception e) {
                System.out.println("TAG --> " + e.getMessage());
            }
        }
    }

**Comment by letson** [comment]
I am having issue to process payment with card reader using tablet Android 7.0. It always return "Unknown device error, please try again". Any help really appreciate. Here is my implemetation. I am using Flutter with calling through methodChannel. Note: I have logged in merchant account successfully.

BigDecimal transAmount = BigDecimal.valueOf(amount);
        EMVTransaction emvTransaction = EMVTransactionManager.createEMVTransaction(AppManager.merchant, transAmount);
        emvTransaction.setEmvTransactionType(EMVTransactionType.PAYMENT);
        EMVTransactionManager.TerminalMode terminalMode = EMVTransactionManager.TerminalMode.SWIPE_OR_INSERT;
        EMVTransactionManager.setTerminalMode(terminalMode);

        EMVDeviceConnectionType deviceConnectionType = EMVDeviceConnectionType.BLUETOOTH;
        EMVTransactionManager.setDeviceConnectionType(deviceConnectionType);

        EMVTransactionManager.startEMVTransaction(emvTransaction, iemvTransaction, context);

**Comment by amitmishra19** [comment]
Hi @letson,

Audio readers running on Android 7.0+ having issues in getting detected. We would suggest you to try "Audio Auto Configuration" to check if the reader can automatically configure itself on the target device.

The API is available through OTAUpdateManager. Please refer to our readme.

**Comment by letson** [comment]
@amitmishra19  Thank you, it was resolved. Thanks for your response.
