### ISSUE TITLE
Refund Integration Issues

### ISSUE THREAD

**Issue by AndroidLoaders** [AuthorizeNet/inperson-sdk-android#44]
Respected sir, 

As per your guidelines(https://github.com/AuthorizeNet/inperson-sdk-android/issues/41) we have implemented code to get transaction details from transaction id and also able to differentiate when to void and refund transaction ... here is a code so that other people can review and implement it..

**## Query** : But we are not getting how can we implement refund and void feature like to get transaction detail you provided package name net.authorize.reporting.TransactionType.GET_TRANSACTION_DETAILS.
So from package name we're able get how to implement.

Also we unable to get how to pass transaction_id when requesting for refund and void transactions with transaction.So if you can also help us for same.

So please provide us some more detailed picture for same or if any working demo and if there is any correction in below code then please inform us so that we can provide best quality to our client.

//TODO : Get details of particular transaction.
    private class GetTransactionDetails extends AsyncTask<String, Integer, net.authorize.reporting.Result> {

        GetTransactionDetails() {
        }

        @Override
        protected void onPreExecute() {
            super.onPreExecute();
            progressDialog.setMessage(getString(R.string.anet_authentication));
            progressDialog.show();
        }

        @Override
        protected net.authorize.reporting.Result doInBackground(String... transactionId) {
            net.authorize.reporting.Result tDetailedResult = null;
            try {
                String deviceId = Build.MANUFACTURER + "_" + Build.MODEL;
                //TODO : First we need to login and Create authentication method based on login, password and device ID
                PasswordAuthentication passAuth = PasswordAuthentication.createMerchantAuthentication(getString(R.string.anet_userName), getString(R.string.anet_password), deviceId);

                //TODO : Create merchant object using authentication method
                Merchant testMerchant = Merchant.createMerchant(Environment.SANDBOX, passAuth);
                testMerchant.createReportingTransaction(TransactionType.GET_TRANSACTION_DETAILS);

                net.authorize.mobile.Transaction loginTransaction = testMerchant.createMobileTransaction(net.authorize.mobile.TransactionType.MOBILE_DEVICE_LOGIN);
                net.authorize.data.mobile.MobileDevice mobileDevice = net.authorize.data.mobile.MobileDevice.createMobileDevice(deviceId, "Device description", "425-555-0000", "Android");
                loginTransaction.setMobileDevice(mobileDevice);

                //TODO : Post login, request to Authorize.net Gateway
                net.authorize.mobile.Result loginResult = (net.authorize.mobile.Result) testMerchant.postTransaction(loginTransaction);
                if (loginResult.isOk()) {
                    publishProgress(1);
                    Thread.sleep(1000);

                    SessionTokenAuthentication sessionTokenAuthentication = SessionTokenAuthentication.createMerchantAuthentication(testMerchant.getMerchantAuthentication().getName(), loginResult.getSessionToken(), "Test EMV Android");//InpersonSDK-Android-test
                    if (loginResult.getSessionToken() != null)
                        testMerchant.setMerchantAuthentication(sessionTokenAuthentication);

                    publishProgress(2);
                    Thread.sleep(1000);

                    ReportingDetails details = ReportingDetails.createReportingDetails();
                    details.setTransactionId(transactionId[0]);

                    net.authorize.reporting.Transaction transaction = Transaction.createTransaction(testMerchant, TransactionType.GET_TRANSACTION_DETAILS);
                    transaction.setReportingDetails(details);

                    tDetailedResult = (Result) testMerchant.postTransaction(transaction);
                }
            } catch (Exception e) {
                System.out.println("TAG --> " + e.getMessage());
            }
            return tDetailedResult;
        }

        @Override
        protected void onProgressUpdate(Integer... values) {
            super.onProgressUpdate(values);
            if (values[0] == 1)
                progressDialog.setMessage(getString(R.string.anet_authentication_successfull));
            else if (values[0] == 2)
                progressDialog.setMessage(getString(R.string.anet_request_transaction_details));
        }

        @Override
        protected void onPostExecute(net.authorize.reporting.Result tDetailedResult) {
            super.onPostExecute(tDetailedResult);
            try {
                progressDialog.dismiss();
                if (tDetailedResult != null) {
                    System.out.println("TAG -- ANET --> response : " + tDetailedResult.getXmlResponse());
                    List<MessageType> mTypeList = tDetailedResult.getMessages();
                    if (mTypeList != null && mTypeList.size() > 0) {
                        String rCode = mTypeList.get(0).getValue();
                        System.out.println("TAG -- ANET --> rCode : " + rCode);
                        if (rCode.equals("I00011"))
                            CommonUtility.alert(activity, getString(R.string.cancel_transaction), getString(R.string.anet_merchant_not_activated));
                        else if (rCode.equals("E00001"))
                            CommonUtility.alert(activity, getString(R.string.cancel_transaction), getString(R.string.anet_system_error));
                        else if (rCode.equals("E00011")) //TODO : No permission
                            new AlertDialog.Builder(activity).setTitle(getString(R.string.cancel_transaction)).setMessage(getString(R.string.anet_no_permission_to_get_transaction_details)).create().show();
                        else if (rCode.equals("I00001")) {//TODO : Successfully got details
                            ReportingDetails details = tDetailedResult.getReportingDetails();
                            List<TransactionDetails> list = details.getTransactionDetailList();
                            if (list != null && list.size() > 0) {
                                TransactionDetails tDetails = list.get(0);
                                TransactionStatusType statusType = tDetails.getTransactionStatus();
                                String text = "";
                                if ((statusType == TransactionStatusType.CAPTURED_PENDING_SETTLEMENT))
                                    Toast.makeText(activity, text = "Transaction can be voided", Toast.LENGTH_SHORT).show();
                                else if (statusType == TransactionStatusType.SETTLED_SUCCESSFULLY)
                                    Toast.makeText(activity, text = "Transaction can request for refund", Toast.LENGTH_SHORT).show();
                                else if (statusType == TransactionStatusType.VOIDED)
                                    Toast.makeText(activity, text = "Transaction already voided", Toast.LENGTH_SHORT).show();
                                else if (statusType == TransactionStatusType.REFUND_PENDING_SETTLEMENT)
                                    Toast.makeText(activity, text = "Transaction refund already in progress", Toast.LENGTH_SHORT).show();
                                else if (statusType == TransactionStatusType.REFUND_SETTLED_SUCCESSFULLY)
                                    Toast.makeText(activity, text = "Transaction already refunded", Toast.LENGTH_SHORT).show();
                                System.out.println("TAG -- ANET --> text : " + text);
                            }
                        }
                    }
                } else
                    CommonUtility.alert(activity, getString(R.string.cancel_transaction), getString(R.string.anet_null_response));
            } catch (Exception e) {
                System.out.println("TAG --> " + e.getMessage());
            }
        }
    }

**Comment by amimishr** [comment]
@AndroidLoaders ,

We are happy that it solved your problem and much appreciate your effort to post your solution here for the developer community.

Regards,
Anet Team
