### ISSUE TITLE
java.lang.RuntimeException: Method code too large!

### ISSUE THREAD

**Issue by sachin-varshney** [AuthorizeNet/inperson-sdk-android#47]
I have tried to run the sample code but encountered with this problem:

Error:Execution failed for task ':app:transformClassesWithInstantRunForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: Method code too large!

**Comment by amimishr** [comment]
@sachin-varshney ,

Could you please disable the "Instant Run" in your Android studio and try again. You can find that option at following path in Android Studio - 

File -> Settings -> "Build, Execution, Deployment".

Regards,
ANET Team

**Comment by sachin-varshney** [comment]
Thanks for the quick response, It worked for me.
