### ISSUE TITLE
Duplicate transaction occur.

### ISSUE THREAD

**Issue by sachin-varshney** [AuthorizeNet/inperson-sdk-android#50]
If I do the transaction of the same amount with the same card then it throws an error duplicate transaction.

I have gone through with this link
 https://support.authorize.net/s/article/Error-11-A-duplicate-transaction-has-been-submitted
 and it says there is a way to adjust the time. let me know how can I set it to 0.

**Comment by amimishr** [comment]
Hi @sachin-varshney 

Ad mentioned in the document you posted, Authorize.NET compares various transaction fields to differentiate if the incoming transaction is duplicate or new.

Some of the possible ways you can use to avoid the duplicate transaction error -
1- Use setDuplicateTxnWindowSeconds() API available in Merchant class to specify the time gap to consider for comparing duplicate transaction. For example

                 merchant.setDuplicateTxnWindowSeconds(30);

will consider a window of 30 seconds. and any transaction with same card and same amount will result in duplicate transaction. You can specify it to a minimum value to 1 sec OR based on your requirement.

Regards,
ANET Team
