### ISSUE TITLE
Problems migrating to AndroidX

### ISSUE THREAD

**Issue by juandapro** [AuthorizeNet/inperson-sdk-android#58]
After migrating my project to AndroidX it no longer compiles. I also tried migrating the SDK sample App and same thing happens, it doesn't compile. I got this error:

ERROR: Unable to resolve dependency for ':app@release/compileClasspath': Failed to transform file 'emv-anet-sdk.aar' to match attributes {artifactType=processed-aar} using transform JetifyTransform
Show Details
Affected Modules: app

thanks

**Comment by amimishr** [comment]
Currently the SDK has not been migrated to AndroidX.
