### ISSUE TITLE
AnywhereCommerce Walker C2X Tap to pay

### ISSUE THREAD

**Issue by nathanoertel** [AuthorizeNet/inperson-sdk-android#66]
We're using the AnywhereCommerce Walker C2X and see that there are only swipe and insert available:
`
public enum TerminalMode{
	SWIPE_ONLY,
	SWIPE_OR_INSERT
}
`
Is there a plan to support tap to pay or is that available some way that I'm not seeing?

**Comment by amimishr** [comment]
@nathanoertel Currently the SDK does not support tap to pay functionality.

**Comment by nathanoertel** [comment]
@amimishr Is there any plan to support that and a timeline on that or is this library dead in the water?

**Comment by amimishr** [comment]
@nathanoertel Definitely there is a plan to expand our Card Present solutions and you will hear some announcements in near future.
