### ISSUE TITLE
Is there a way to send an invoice number to authorize.net?

### ISSUE THREAD

**Issue by cmcfatter** [AuthorizeNet/inperson-sdk-android#71]
In order to go forward with this app I would need to be able to send the invoice number to authorize.net. Currently the invoice field is blank when I process transactions. Is there a way to do that?

**Comment by amimishr** [comment]
@cmcfatter Yes there is a way. 
First you can create an Order object, this order object has method to setup invoice number. Then assign this order object to your EmvTransaction object.

**Comment by cmcfatter** [comment]
Thank you so much for your quick answer! I am attempting to create the order object but I am getting an error that says "'Order()' has protected access in 'net.authorize.data.Order'. Here is my code:

    View.OnClickListener mListner = new View.OnClickListener() {

        public void onClick(View view) {
            if (AppManager.merchant == null) {
                Intent i = new Intent(context, LoginActivity.class);
                i.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                startActivity(i);
                finish();
                return;
            }

            String strAmount = "1.00";
            BigDecimal decAmount = new BigDecimal(strAmount);
            double dbAmount = Double.parseDouble(strAmount);


            EMVTransaction emvTransaction = EMVTransactionManager.createEMVTransaction(AppManager.merchant, decAmount);

            Log.d("Created transaction", "created transaction");

            emvTransaction.setEmvTransactionType(EMVTransactionType.GOODS);

            net.authorize.data.Order testOrder = new net.authorize.data.Order();        //this is where I'm getting the error
            testOrder.setInvoiceNumber("12345678");
            emvTransaction.setOrder(testOrder);


            if (dbAmount > 0){
                if (view == chargeCreditCardBtn){
                    createProfile = false;
                    customerProfileId = null;
                    //EMVTransactionManager.startEMVTransaction(emvTransaction, intemvTransaction, context);
                    EMVTransactionManager.startQuickChipTransaction(emvTransaction, iemvTransaction, context);
                    Log.d("Starting transaction", "starting transaction");
                }
            }

        }
    };

**Comment by cmcfatter** [comment]
Disregard last question, I realized I was using the wrong order reference

**Comment by cmcfatter** [comment]
I just realized that I should be using Order instead of net.authorize.data.Order() but I'm still getting the same error with that.

**Comment by cmcfatter** [comment]
Thank you so much for your help, I just got it to send the invoice number!

**Comment by amimishr** [comment]
Please use net.authorize.data.Order.createOrder() to create a new order.
