### ISSUE TITLE
Error with transaction reporting. What is AnetHelper?

### ISSUE THREAD

**Issue by cmcfatter** [AuthorizeNet/inperson-sdk-android#74]
I am trying to perform transaction reporting but am getting this error: "android.os.NetworkOnMainThreadException." The error is occurring when I try to post the reporting transaction using this code:

net.authorize.reporting.Result result = null;
net.authorize.reporting.Transaction t = AppManager.merchant.createReportingTransaction(TransactionType.GET_UNSETTLED_TRANSACTION_LIST);

result = (net.authorize.reporting.Result) AppManager.merchant.postTransaction(t); //this is where the error is occurring

The reporting section in the documentation shows this as the correct statement but I have no idea what AnetHelper is and it doesn't explain it at all:

result = (net.authorize.reporting.Result) AnetHelper.merchant.postTransaction(t);

Can anyone tell me what AnetHelper is or how I can correct my code?

**Comment by amimishr** [comment]
The above error is not specific to usage of AnetHelpr. Basically you might be executing the above statements from UI/Main thread. In Android it is not permitted hence the exception. Please refer to the following link 

https://developer.android.com/reference/android/os/NetworkOnMainThreadException

I would suggest to make the above calls out of UI thread.

**Comment by cmcfatter** [comment]
Thanks for your quick answer
