### ISSUE TITLE
How to get transaction ID from Non-EMV transaction

### ISSUE THREAD

**Issue by cmcfatter** [AuthorizeNet/inperson-sdk-android#79]
I am creating an option for customers to key in their card info rather than swiping. It's my understanding so far that this sort of transaction would be a non-EMV transaction. I have it working but I am wondering how the transaction ID can be retrieved after the transaction has posted. 
With the transactions where the customer swipes/inserts their card, it's incredibly easy to retrieve the transaction ID just by using something like this:
net.authorize.aim.emv.Result result;
result.getTransID();

I don't see this option for non-EMV transactions. Can anyone point me in the right direction?

**Comment by grap4082** [comment]
Approval transfers to card refund merchandise
